-- Sprint 3: Initial Database Schema
-- RPGate Telegram Bot - Memory System & Persistence

-- Enable pgvector extension for semantic search
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================
-- TABLE: characters
-- ============================================
CREATE TABLE characters (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    telegram_user_id BIGINT UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    
    -- Character stats (JSON for flexibility)
    character_sheet JSONB NOT NULL,
    
    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_session_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_characters_telegram_user_id ON characters(telegram_user_id);
CREATE INDEX idx_characters_updated_at ON characters(updated_at DESC);

-- ============================================
-- TABLE: game_sessions
-- ============================================
CREATE TABLE game_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    character_id UUID NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    
    -- Session info
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ended_at TIMESTAMP WITH TIME ZONE,
    
    -- Session summary (generated by LLM after session ends)
    summary TEXT,
    
    -- Stats
    turns_count INT DEFAULT 0,
    total_damage_dealt INT DEFAULT 0,
    total_damage_taken INT DEFAULT 0,
    
    CONSTRAINT fk_character FOREIGN KEY (character_id) REFERENCES characters(id)
);

CREATE INDEX idx_sessions_character_id ON game_sessions(character_id);
CREATE INDEX idx_sessions_started_at ON game_sessions(started_at DESC);

-- ============================================
-- TABLE: episodic_memories
-- ============================================
CREATE TABLE episodic_memories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    character_id UUID NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    session_id UUID REFERENCES game_sessions(id) ON DELETE SET NULL,
    
    -- Memory content
    content TEXT NOT NULL,
    
    -- Vector embedding для semantic search
    embedding VECTOR(2000),  -- qwen/qwen3-embedding-8b dimension (limited to 2000 for pgvector)
    
    -- Memory metadata
    memory_type VARCHAR(50) DEFAULT 'event',  -- 'event', 'dialogue', 'discovery', 'combat'
    importance_score INT DEFAULT 5 CHECK (importance_score >= 0 AND importance_score <= 10),
    
    -- Entities for keyword filtering
    entities TEXT[],  -- ['goblin', 'tavern', 'Eldar the merchant']
    location VARCHAR(200),
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT fk_character FOREIGN KEY (character_id) REFERENCES characters(id),
    CONSTRAINT fk_session FOREIGN KEY (session_id) REFERENCES game_sessions(id)
);

CREATE INDEX idx_memories_character_id ON episodic_memories(character_id);
CREATE INDEX idx_memories_session_id ON episodic_memories(session_id);
CREATE INDEX idx_memories_created_at ON episodic_memories(created_at DESC);
CREATE INDEX idx_memories_importance ON episodic_memories(importance_score DESC);

-- Vector similarity search index (HNSW for better performance)
CREATE INDEX idx_memories_embedding ON episodic_memories 
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- GIN index for entities array search
CREATE INDEX idx_memories_entities ON episodic_memories USING GIN(entities);

-- ============================================
-- TABLE: semantic_memories (World Lore)
-- ============================================
CREATE TABLE semantic_memories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Content
    content TEXT NOT NULL,
    category VARCHAR(50) NOT NULL,  -- 'rule', 'lore', 'location', 'npc', 'item'
    
    -- Vector embedding
    embedding VECTOR(2000),
    
    -- Metadata
    tags TEXT[],
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_semantic_category ON semantic_memories(category);
CREATE INDEX idx_semantic_embedding ON semantic_memories 
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- ============================================
-- TABLE: world_state (Global/per-character state)
-- ============================================
CREATE TABLE world_state (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    character_id UUID NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    
    -- World state as JSON
    state_data JSONB NOT NULL DEFAULT '{}',
    
    -- For tracking changes
    version INT DEFAULT 1,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT fk_character FOREIGN KEY (character_id) REFERENCES characters(id),
    CONSTRAINT unique_character_state UNIQUE (character_id)
);

CREATE INDEX idx_world_state_character_id ON world_state(character_id);

-- ============================================
-- FUNCTIONS: Auto-update timestamps
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_characters_updated_at
    BEFORE UPDATE ON characters
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_semantic_updated_at
    BEFORE UPDATE ON semantic_memories
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_world_state_updated_at
    BEFORE UPDATE ON world_state
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- SAMPLE DATA: Semantic Memories (Game Lore)
-- ============================================
INSERT INTO semantic_memories (content, category, tags) VALUES
    ('В этом мире магия запрещена королевским указом после Великой Магической Катастрофы. Использование заклинаний карается смертью.', 'lore', ARRAY['magic', 'law', 'history']),
    ('Город Новоград — крупнейший торговый центр королевства. Здесь можно купить любые товары, от простых инструментов до редких артефактов.', 'location', ARRAY['city', 'trade', 'Новоград']),
    ('Гоблины обитают в пещерах северных гор. Они агрессивны, но трусливы. AC: 12, HP: 7, атака: +4 (1d6+2 урона).', 'npc', ARRAY['goblin', 'enemy', 'combat']),
    ('Для проверки атаки брось d20 и прибавь модификатор силы. Если результат больше или равен AC противника — попадание.', 'rule', ARRAY['combat', 'attack', 'mechanics']);
